"""Add job and job_source tables

Revision ID: 293aaf4729a6
Revises: 8e796f013f86
Create Date: 2026-08-13 01:15:31.162829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '293aaf4729a6'
down_revision: Union[str, None] = '8e796f013f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###