"""Add candidate profile table

Revision ID: 8e796f013f86
Revises: 
Create Date: 2026-08-13 01:06:27.304788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8e796f013f86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('desired_positions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('desired_salary_min', sa.Integer(), nullable=True),
    sa.Column('desired_salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=False),
    sa.Column('employment_types', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('work_formats', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('relocation_possible', sa.Boolean(), nullable=False),
    sa.Column('business_trips_acceptable', sa.Boolean(), nullable=False),
    sa.Column('resume_versions', sa.JSON(), nullable=False),
    sa.Column('additional_preferences', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###